repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/dnanhkhoa/nb_black
    rev: 7a9a47cdf7c19248ad2d62576dc5342f687b3a71
    hooks:
      - id: nb_black

  - repo: https://github.com/kynan/nbstripout
    rev: v0.5.0
    hooks:
      - id: nbstripout

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--fix", "--output-format=full"]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

